"""兼容层 — 从 app.prompts.writing 导入学术写作辅助提示词"""

from app.prompts.writing import (  # noqa: F401
    GENERATE_REVIEW_PROMPT,
    GENERATE_OUTLINE_PROMPT,
    GENERATE_DRAFT_PROMPT,
    POLISH_TEXT_PROMPT,
    CITATION_FORMAT_TEMPLATES,
    CITATION_SYSTEM_PROMPT,
)

__all__ = [
    "GENERATE_REVIEW_PROMPT",
    "GENERATE_OUTLINE_PROMPT",
    "GENERATE_DRAFT_PROMPT",
    "POLISH_TEXT_PROMPT",
    "CITATION_FORMAT_TEMPLATES",
    "CITATION_SYSTEM_PROMPT",
]
