"""initial_schema

Revision ID: 6895243c431d
Revises: 
Create Date: 2026-04-18 01:16:18.114777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6895243c431d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_paper_id'), 'chat_sessions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_highlights_paper_id'), 'highlights', ['paper_id'], unique=False)
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_cards_paper_id'), 'knowledge_cards', ['paper_id'], unique=False)
    op.create_index(op.f('ix_knowledge_cards_user_id'), 'knowledge_cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_paper_text_blocks_paper_id'), 'paper_text_blocks', ['paper_id'], unique=False)
    op.alter_column('papers', 'analysis_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'not_generated'"))
    op.create_index(op.f('ix_papers_reading_status'), 'papers', ['reading_status'], unique=False)
    op.create_index(op.f('ix_papers_user_id'), 'papers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_user_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_reading_status'), table_name='papers')
    op.alter_column('papers', 'analysis_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'not_generated'"))
    op.drop_index(op.f('ix_paper_text_blocks_paper_id'), table_name='paper_text_blocks')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_index(op.f('ix_knowledge_cards_user_id'), table_name='knowledge_cards')
    op.drop_index(op.f('ix_knowledge_cards_paper_id'), table_name='knowledge_cards')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_paper_id'), table_name='highlights')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_paper_id'), table_name='chat_sessions')
    # ### end Alembic commands ###
