"""add_performance_indexes

Revision ID: 6b06f2d59928
Revises: 6895243c431d
Create Date: 2026-04-19 06:25:30.363565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b06f2d59928'
down_revision: Union[str, Sequence[str], None] = '6895243c431d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_paper_id'), 'chat_sessions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_highlights_paper_id'), 'highlights', ['paper_id'], unique=False)
    op.create_index('ix_highlights_paper_page', 'highlights', ['paper_id', 'page'], unique=False)
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_cards_paper_id'), 'knowledge_cards', ['paper_id'], unique=False)
    op.create_index(op.f('ix_knowledge_cards_user_id'), 'knowledge_cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_paper_text_blocks_paper_id'), 'paper_text_blocks', ['paper_id'], unique=False)
    op.create_index('ix_textblocks_paper_page', 'paper_text_blocks', ['paper_id', 'page_number', 'y0'], unique=False)
    with op.batch_alter_table('papers') as batch_op:
        batch_op.alter_column('analysis_status',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=False,
                   existing_server_default=sa.text("'not_generated'"))
    op.create_index(op.f('ix_papers_reading_status'), 'papers', ['reading_status'], unique=False)
    op.create_index(op.f('ix_papers_user_id'), 'papers', ['user_id'], unique=False)
    op.create_index('ix_papers_user_status', 'papers', ['user_id', 'reading_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_user_status', table_name='papers')
    op.drop_index(op.f('ix_papers_user_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_reading_status'), table_name='papers')
    with op.batch_alter_table('papers') as batch_op:
        batch_op.alter_column('analysis_status',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True,
                   existing_server_default=sa.text("'not_generated'"))
    op.drop_index('ix_textblocks_paper_page', table_name='paper_text_blocks')
    op.drop_index(op.f('ix_paper_text_blocks_paper_id'), table_name='paper_text_blocks')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_index(op.f('ix_knowledge_cards_user_id'), table_name='knowledge_cards')
    op.drop_index(op.f('ix_knowledge_cards_paper_id'), table_name='knowledge_cards')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index('ix_highlights_paper_page', table_name='highlights')
    op.drop_index(op.f('ix_highlights_paper_id'), table_name='highlights')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_paper_id'), table_name='chat_sessions')
    op.drop_index('ix_messages_session_created', table_name='chat_messages')
    # ### end Alembic commands ###
